language: python
dist: xenial
python:
  - "2.7"
  - "3.7"
branches:
  only:
  - master
script:
  - make coverage
  - coverage xml
  - coveralls
  - make build
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "./pyex"
  skip_cleanup: true
  on:
    branch: master
    python: "3.7"
    tags: true
